apiVersion: v1
kind: Pod
metadata:
  name: pod-error2
  namespace: pod-error
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'Crashed!' `date`"]  # Container will crash immediately

