apiVersion: v1
kind: Pod
metadata:
  name: readiness-probe-failure
spec:
      containers:
      - name: readiness-probe-container
        image: busybox
        command: ["sh", "-c", "sleep 3600"] # Keep the container running
        readinessProbe:
          exec:
            command:
            - cat
            - /non-existent-file # File that doesn't exist
          initialDelaySeconds: 5
          periodSeconds: 10
