apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-error
spec:
  containers:
  - name: slow-start-container
    image: busybox
    command:
    - sh
    - -c
    - |
      echo "Starting application...";
      sleep 30; # Simulate a slow application startup
      echo "Application is now running.";
      sleep 3600; # Keep the container running
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 1 # Very small delay; the probe will start checking immediately
      periodSeconds: 5       # Probe checks every 5 seconds
    ports:
    - containerPort: 8080
