apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    command:
    - sh
    - -c
    - |
      echo "Simulating slow nginx startup...";
      sleep 05; # Simulate delay before nginx starts
      nginx -g "daemon off;" # Start nginx after delay
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 1 # Very small delay causes probe to fail
      periodSeconds: 1
      failureThreshold: 1    # Fail quickly
    ports:
    - containerPort: 80
