apiVersion: v1
kind: Pod
metadata:
  name: failed-scheduling-pod
  namespace: sched-err
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      resources:
        requests:
          memory: "64Gi"
          cpu: "32"
        limits:
          memory: "64Gi"
          cpu: "32"
---
apiVersion: v1
kind: Node
metadata:
  name: node
  namespace: sched-err
spec:
  taints:
    - key: "node.kubernetes.io/unreachable"
      effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: node-selector-mismatch-pod
  namespace: sched-err
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
  nodeSelector:
    disktype: ssd
---
apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-mismatch-pod
  namespace: sched-err
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - hdd
---
apiVersion: v1
kind: Node
metadata:
  name: untolerated-taints-node
  namespace: sched-err
spec:
  taints:
    - key: "example.com/untolerated"
      value: "true"
      effect: "NoSchedule"
---
apiVersion: v1
kind: Pod
metadata:
  name: untolerated-taints-pod
  namespace: sched-err
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
  tolerations:
    - key: "example.com/tolerated"
      operator: "Exists"
      effect: "NoSchedule"
