apiVersion: v1
kind: Pod
metadata:
  name: volume-permission-denied
  namespace: vol-errs
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'touch /mnt/data/test.txt && sleep 3600']
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/data
  volumes:
  - name: test-volume
    hostPath:
      path: /root/data
      type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: invalid-volume-spec
  namespace: vol-errs
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/data
  volumes:
  - name: test-volume
    invalidField: invalidValue
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-mount-conflict
  namespace: vol-errs
spec:
  containers:
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/data
  - name: busybox2
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/data
  volumes:
  - name: test-volume
    emptyDir: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-binding-failed-pv
  namespace: vol-errs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: invalid-server
    path: "/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-binding-failed-pvc
  namespace: vol-errs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: volume-binding-failed
  namespace: vol-errs
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/data
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: volume-binding-failed-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-limit-exceeded
  namespace: vol-errs
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: test-volume-1
      mountPath: /mnt/data1
    - name: test-volume-2
      mountPath: /mnt/data2
    - name: test-volume-3
      mountPath: /mnt/data3
    - name: test-volume-4
      mountPath: /mnt/data4
    - name: test-volume-5
      mountPath: /mnt/data5
    - name: test-volume-6
      mountPath: /mnt/data6
  volumes:
  - name: test-volume-1
    emptyDir: {}
  - name: test-volume-2
    emptyDir: {}
  - name: test-volume-3
    emptyDir: {}
  - name: test-volume-4
    emptyDir: {}
  - name: test-volume-5
    emptyDir: {}
  - name: test-volume-6
    emptyDir: {}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: invalid-provisioner
  namespace: vol-errs
provisioner: invalid/provisioner

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provisioning-failed-pvc
  namespace: vol-errs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: invalid-provisioner
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: provisioning-failed
  namespace: vol-errs
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/data
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: provisioning-failed-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-unmount-failed
  namespace: vol-errs
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/data
  volumes:
  - name: test-volume
    nfs:
      server: invalid-server
      path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-resize-failed-pvc
  namespace: vol-errs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-resize-failed-pv
  namespace: vol-errs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: invalid-server
    path: "/"

---

apiVersion: v1
kind: Pod
metadata:
  name: volume-resize-failed
  namespace: vol-errs
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/data
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: volume-resize-failed-pvc
